### ISSUE TITLE
A5ultexx builds

### ISSUE THREAD

**Issue by krmax44** [Galaxy-MSM8916/releases#2]
Hi,

I'd like to ask whether we could get A5ultexx builds as well, the device configs and stuff all are available and seem ready to use.

Thanks!

**Comment by maguasvanin** [comment]
Hi,
Sorry. I think you are confused. I have a Samsung Galaxy Gran Prime SM-G530M
(fortunalteub), running the LineageOS' custom ROM 15.5. I don't Kwon
anything about A5ultexx  builds. I never used it.

Greetings

**Comment by krmax44** [comment]
Sorry, yes - I just saw the a5-common repo but the specific a5ultexx repo is from someone else.
